---
  - hosts: all
    become: true
    gather_facts: false
    tasks:
      - name: install os packages
        package:
          name:
            - curl
            - wget
            - mc
          state: present

      - name: setup proxy env
        copy:
          dest: /etc/profile.d/proxy.sh
          content: |
            export http_proxy=http://192.168.55.3:3128/
            export https_proxy=http://192.168.55.3:3128/
